import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "../app/components/Footer";
import Header from "../app/components/Header";
import Loading from "./components/Loading";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const customFont = localFont({
  src: [
    {
      path: "../app/assets/fonts/LavaPro_HL-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../app/assets/fonts/LavaPro_HL-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../app/assets/fonts/LavaPro_HL-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--custom-font",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${customFont.className} antialiased`}>
        <Loading />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
